GenerationConfig = {
    "question-answering": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 100,
        "repetition_penalty": 1.1,
    },
    "summarization": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 300,
        "repetition_penalty": 1.1,
    },
    "translation_envi": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 500,
        "repetition_penalty": 1.1,
    },
    "translation_vien": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 500,
        "repetition_penalty": 1.1,
    },
    "language-modelling_filling": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 500,
        "repetition_penalty": 1.1,
    },
    "language-modelling_correction": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 500,
        "repetition_penalty": 1.1,
    },
    "sentiment-analysis": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "text-classification_vsmec": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "text-classification_atis": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "toxic-detection": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "knowledge_mtpchoice": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "knowledge_openended": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 100,
        "repetition_penalty": 1.1,
    },
    "information-retrieval": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 50,
        "repetition_penalty": 1.1,
    },
    "reasoning_synthetic": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 100,
        "repetition_penalty": 1.1,
    },
    "reasoning_math": {
        "temperature": 1.0,
        "top_k": 1,
        "max_new_tokens": 1000,
        "repetition_penalty": 1.1,
    },
}
